import CommonCrypto
import Foundation

/// Return random bytes.
/// - Parameter count: Number of random bytes to return.
/// - Throws: A `CryptoError` describing the issue.
/// - Returns: The randomly generated bytes.
public func CCRandomGenerateBytes(count: Int) throws -> Data {
    var bytes = [UInt8](repeating: 0, count: count)
    let status = CCCryptorStatus(CommonCrypto.CCRandomGenerateBytes(&bytes, count))
    guard status == .success else { throw CryptoError(status) }
    return Data(bytes)
}
